/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import javax.swing.JOptionPane;
import kong.unirest.json.JSONObject;
import models.SaurioClass;
import utils.APIHandler;

/**
 *
 * @author mañana
 */
public class DataSaurioPanel extends javax.swing.JPanel {

    /**
     * Creates new form DataSaurioPanel
     */
    public DataSaurioPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tx_nombresaurio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_poder = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tx_edad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tx_alimentacion = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Kievit Offc Pro", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATASAURIO");

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Kievit Offc Pro", 1, 18)); // NOI18N
        jButton1.setText("DINO CREAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        jLabel2.setFont(new java.awt.Font("Kievit Offc Pro", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre Saurio:");
        jPanel1.add(jLabel2);

        tx_nombresaurio.setFont(new java.awt.Font("Kievit Offc Pro", 1, 18)); // NOI18N
        jPanel1.add(tx_nombresaurio);

        jLabel3.setFont(new java.awt.Font("Kievit Offc Pro", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Poder:");
        jPanel1.add(jLabel3);

        cb_poder.setFont(new java.awt.Font("Kievit Offc Pro", 1, 14)); // NOI18N
        cb_poder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mordisco", "Fuego", "Ataque veloz", " " }));
        jPanel1.add(cb_poder);

        jLabel5.setFont(new java.awt.Font("Kievit Offc Pro", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Edad:");
        jPanel1.add(jLabel5);

        tx_edad.setFont(new java.awt.Font("Kievit Offc Pro", 1, 18)); // NOI18N
        jPanel1.add(tx_edad);

        jLabel4.setFont(new java.awt.Font("Kievit Offc Pro", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Alimentación:");
        jPanel1.add(jLabel4);

        tx_alimentacion.setFont(new java.awt.Font("Kievit Offc Pro", 1, 18)); // NOI18N
        jPanel1.add(tx_alimentacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 242, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(368, 368, 368))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        var saurio = new SaurioClass();
        saurio.setNombreSaurio(tx_nombresaurio.getText());
        saurio.setDinoAge(Integer.parseInt(tx_edad.getText()));
        saurio.setAlimentacion(tx_alimentacion.getText());
        saurio.setPoder((String) cb_poder.getSelectedItem());
        var variable = "hola";
        JSONObject respuestaCrear = (JSONObject) APIHandler.createSaurio(saurio);
        if(respuestaCrear.get("code_response").equals(0)){
            
        }
        
        JOptionPane.showMessageDialog(null, (String) respuestaCrear.get("message"));
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_poder;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tx_alimentacion;
    private javax.swing.JTextField tx_edad;
    private javax.swing.JTextField tx_nombresaurio;
    // End of variables declaration//GEN-END:variables
}
